#spring:
#  application:
#    name: AppointmentService
#  datasource:
#    url: jdbc:mysql://localhost:3306/himsdb?useSSL=false&serverTimezone=UTC
#    username: root
#    password: Root123$
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  cloud:
#    config: 
#      enabled: false
#server:
#  port: 8095
#
#eureka:
#  client: 
#    service-url: 
#     defaultZone: http://localhost:8761/eureka
#resilience4j: 
#  circuitbreaker: 
#    instances: 
#      DoctorService: 
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10 
#        failureRateThreshold: 50 
#        waitDurationInOpenState: 10000 
#        permittedNumberOfCallsInHalfOpenState: 3 
#        automaticTransitionFromOpenToHalfOpenEnabled: true 
#  retry: 
#    instances: 
#      DoctorService: 
#      maxAttempts: 3 
#      waitDuration: 500
#logging: 
#    level:
#      '[com.hospital.AppointmentService.openFeign]': INFO
spring:
  application:
    name: AppointmentService
  datasource:
    url: jdbc:mysql://localhost:3306/himsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Root123$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    config: 
      enabled: false

server:
  port: 8095

eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka

resilience4j: 
  circuitbreaker: 
    instances: 
      DoctorService:        # must match annotation name exactly
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10 
        failureRateThreshold: 50 
        waitDurationInOpenState: 10s   # use time units like "10s"
        permittedNumberOfCallsInHalfOpenState: 3 
        automaticTransitionFromOpenToHalfOpenEnabled: true 
  retry: 
    instances: 
      DoctorService:        # must match annotation name exactly
        maxAttempts: 3 
        waitDuration: 500ms # use time units like "ms", "s"

logging: 
  level:
    com.hospital.AppointmentService.openFeign: INFO
